"""increase decimal precision for metric values to 3 places

Revision ID: 273d31ea2672
Revises: 94ce897f82f8
Create Date: 2026-01-05 18:53:33.914328

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "273d31ea2672"
down_revision: Union[str, Sequence[str], None] = "94ce897f82f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity_metrics",
        "value",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.DECIMAL(precision=10, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "body_metrics",
        "value",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.DECIMAL(precision=10, scale=3),
        existing_nullable=False,
    )
    op.alter_column(
        "heart_rate_metrics",
        "value",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.DECIMAL(precision=10, scale=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "heart_rate_metrics",
        "value",
        existing_type=sa.DECIMAL(precision=10, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "body_metrics",
        "value",
        existing_type=sa.DECIMAL(precision=10, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    op.alter_column(
        "activity_metrics",
        "value",
        existing_type=sa.DECIMAL(precision=10, scale=3),
        type_=sa.NUMERIC(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
