"""add workouts table

Revision ID: 69485b6ad5b7
Revises: 4a9decd62302
Create Date: 2026-01-06 18:07:35.207330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69485b6ad5b7"
down_revision: Union[str, Sequence[str], None] = "4a9decd62302"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("workout_type", sa.String(length=50), nullable=False),
        sa.Column("start_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("end_time", sa.TIMESTAMP(), nullable=False),
        sa.Column(
            "duration_minutes", sa.DECIMAL(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "active_energy_kcal", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "basal_energy_kcal", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "total_energy_kcal", sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column("distance_km", sa.DECIMAL(precision=10, scale=3), nullable=True),
        sa.Column("avg_heart_rate_bpm", sa.Integer(), nullable=True),
        sa.Column("min_heart_rate_bpm", sa.Integer(), nullable=True),
        sa.Column("max_heart_rate_bpm", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("indoor_workout", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_time > start_time", name="ck_valid_workout_duration"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "start_time", name="uq_workout"),
    )
    op.create_index(
        "idx_workouts_user_type_date",
        "workouts",
        ["user_id", "workout_type", "start_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_workouts_user_type_date", table_name="workouts")
    op.drop_table("workouts")
    # ### end Alembic commands ###
